=== karadsik7/web_study/ch28_xml/WebContent/car.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cars (car*)>
<!ELEMENT car (model, company, color+)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT company (name, ceo)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT ceo (#PCDATA)>
<!ELEMENT color (#PCDATA)>

<!ATTLIST car id ID #REQUIRED>

=== karadsik7/web_study/ch28_xml/WebContent/car.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cars SYSTEM "car.dtd">
<cars>
	<car id="a">
		<model>sonata</model>
		<company>
			<name>hyundai</name>
			<ceo>정몽구</ceo>
		</company>
		<color>blue</color>
		<color>red</color>
	</car>
	<car id="b">
		<model>K5</model>
		<company>
			<name>hyundai</name>
			<ceo>정몽구</ceo>
		</company>
		<color>black</color>
	</car>
	
</cars>
