=== karadsik7/web_study/ch28_xml/WebContent/table.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT table (caption?, tr*)>
<!-- <!ELEMENT caption EMPTY> -->
<!-- <!ELEMENT tr ANY> -->

<!ELEMENT caption (#PCDATA)>
<!ELEMENT tr (th*, td*)>
<!ELEMENT th ANY>
<!ELEMENT td ANY>

<!ATTLIST th colspan CDATA "1">
<!ATTLIST td colspan CDATA "1">

=== karadsik7/web_study/ch28_xml/WebContent/table.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "table.dtd">
<table>
	<caption>성적관리시스템</caption>
	<tr>
		<th>국어</th>
		<th>수학</th>
		<th colspan="2">영어</th>
	</tr>
	<tr>
		<td>100</td>
		<td>50</td>
		<td>0ㅇㅁㄹ</td>
	</tr>
</table>
